language: python
sudo: false


addons:
  apt:
    packages:
      - gfortran
      - netcdf-bin
      - libnetcdf-dev

install:
  - pip install xarray

script:
  - nc-config --all
  - mkdir build/
  - cmake ..
  - ls -R /home/travis/build
  - make main
  - make check
