language: python
sudo: false


addons:
  apt:
    packages:
      - gfortran
      - netcdf-bin
      - libnetcdf-dev

install:
  - pip install xarray

script:
  - nc-config --all
  - cmake .
  - make main
  - make check
